# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99803c16277c276f808fb3ccb54871311554bf2ed4ca737e827145cd44475b190f510ce139142fdc5ec8696ad6bc615573fc07795f9a5543857ed637efa37989
  FACEBOOK_APP_ID: <%= ENV["FACEBOOK_APP_ID"] %>
  FACEBOOK_APP_SECRET: <%= ENV["FACEBOOK_APP_SECRET"] %>

test:
  secret_key_base: 5d26fd477b267f77bf06257ce28ed54fafb53777ca3275ce6505eb8eedb58d12adcab7482eb5331e549caf01a2084b893c29ca8710068dcdfbf98fe80e319904
  FACEBOOK_APP_ID: <%= ENV["FACEBOOK_APP_ID"] %>
  FACEBOOK_APP_SECRET: <%= ENV["FACEBOOK_APP_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  FACEBOOK_APP_ID: <%= ENV["FACEBOOK_APP_ID"] %>
  FACEBOOK_APP_SECRET: <%= ENV["FACEBOOK_APP_SECRET"] %>
